// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SE2025.Data;

#nullable disable

namespace SE2025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SE2025.Models.Carer", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<string>("Availability_Schedule")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.ToTable("Carers");

                    b.HasData(
                        new
                        {
                            User_ID = 1,
                            Availability_Schedule = "Mon-Fri 9am-5pm"
                        },
                        new
                        {
                            User_ID = 2,
                            Availability_Schedule = "Tue-Thu 10am-4pm"
                        });
                });

            modelBuilder.Entity("SE2025.Models.Carer_Access", b =>
                {
                    b.Property<int>("Access_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Access_ID"));

                    b.Property<int>("Carer_User_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Granted_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Granted_By_User_ID")
                        .HasColumnType("int");

                    b.Property<int>("Patient_User_ID")
                        .HasColumnType("int");

                    b.Property<int>("Permission_Level")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Revoked_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("Revoked_By_User_ID")
                        .HasColumnType("int");

                    b.HasKey("Access_ID");

                    b.HasIndex("Carer_User_ID");

                    b.HasIndex("Patient_User_ID");

                    b.ToTable("Carer_Accesses");

                    b.HasData(
                        new
                        {
                            Access_ID = 1,
                            Carer_User_ID = 1,
                            Granted_At = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Granted_By_User_ID = 5,
                            Patient_User_ID = 3,
                            Permission_Level = 2,
                            Revoked_By_User_ID = 0
                        },
                        new
                        {
                            Access_ID = 2,
                            Carer_User_ID = 1,
                            Granted_At = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Granted_By_User_ID = 5,
                            Patient_User_ID = 4,
                            Permission_Level = 3,
                            Revoked_By_User_ID = 0
                        },
                        new
                        {
                            Access_ID = 3,
                            Carer_User_ID = 2,
                            Granted_At = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Granted_By_User_ID = 5,
                            Patient_User_ID = 3,
                            Permission_Level = 1,
                            Revoked_By_User_ID = 0
                        });
                });

            modelBuilder.Entity("SE2025.Models.Gender", b =>
                {
                    b.Property<int>("Gender_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gender_ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Gender_ID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Gender_ID = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Gender_ID = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Gender_ID = 3,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("SE2025.Models.Patient", b =>
                {
                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender_ID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_ID");

                    b.HasIndex("Gender_ID");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            User_ID = 3,
                            Date_of_Birth = new DateTime(1985, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender_ID = 2,
                            Notes = "N/A"
                        },
                        new
                        {
                            User_ID = 4,
                            Date_of_Birth = new DateTime(1992, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gender_ID = 1,
                            Notes = "N/A"
                        });
                });

            modelBuilder.Entity("SE2025.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Activation_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_Activated")
                        .HasColumnType("bit");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_Type_ID")
                        .HasColumnType("int");

                    b.HasKey("User_ID");

                    b.HasIndex("User_Type_ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_ID = 1,
                            Activation_Code = "ABC123",
                            Created_At = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.smith@example.com",
                            First_Name = "John",
                            Is_Activated = true,
                            Last_Name = "Smith",
                            Password_Hash = "hash123",
                            Status = "Active",
                            Title = "Mr",
                            User_Type_ID = 4
                        },
                        new
                        {
                            User_ID = 2,
                            Activation_Code = "DEF456",
                            Created_At = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.j@example.com",
                            First_Name = "Sarah",
                            Is_Activated = true,
                            Last_Name = "Johnson",
                            Password_Hash = "hash456",
                            Status = "Active",
                            Title = "Ms",
                            User_Type_ID = 4
                        },
                        new
                        {
                            User_ID = 3,
                            Activation_Code = "GHI789",
                            Created_At = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.w@example.com",
                            First_Name = "Emma",
                            Is_Activated = true,
                            Last_Name = "Williams",
                            Password_Hash = "hash789",
                            Status = "Active",
                            Title = "Mrs",
                            User_Type_ID = 3
                        },
                        new
                        {
                            User_ID = 4,
                            Activation_Code = "JKL101",
                            Created_At = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.b@example.com",
                            First_Name = "Michael",
                            Is_Activated = true,
                            Last_Name = "Brown",
                            Password_Hash = "hash101",
                            Status = "Active",
                            Title = "Mr",
                            User_Type_ID = 3
                        },
                        new
                        {
                            User_ID = 5,
                            Activation_Code = "MNO202",
                            Created_At = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dr.anderson@example.com",
                            First_Name = "Lisa",
                            Is_Activated = true,
                            Last_Name = "Anderson",
                            Password_Hash = "hash202",
                            Status = "Active",
                            Title = "Dr",
                            User_Type_ID = 2
                        });
                });

            modelBuilder.Entity("SE2025.Models.User_Type", b =>
                {
                    b.Property<int>("User_Type_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_Type_ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_Type_ID");

                    b.ToTable("User_Types");

                    b.HasData(
                        new
                        {
                            User_Type_ID = 1,
                            Description = "N/A",
                            Type_Name = "Admin"
                        },
                        new
                        {
                            User_Type_ID = 2,
                            Description = "N/A",
                            Type_Name = "Clinician"
                        },
                        new
                        {
                            User_Type_ID = 3,
                            Description = "N/A",
                            Type_Name = "Patient"
                        },
                        new
                        {
                            User_Type_ID = 4,
                            Description = "N/A",
                            Type_Name = "Carer"
                        });
                });

            modelBuilder.Entity("SE2025.Models.Carer", b =>
                {
                    b.HasOne("SE2025.Models.User", "User")
                        .WithOne("Carer")
                        .HasForeignKey("SE2025.Models.Carer", "User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SE2025.Models.Carer_Access", b =>
                {
                    b.HasOne("SE2025.Models.Carer", "Carer")
                        .WithMany("Carer_Accesses")
                        .HasForeignKey("Carer_User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SE2025.Models.Patient", "Patient")
                        .WithMany("CarerAccess")
                        .HasForeignKey("Patient_User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carer");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("SE2025.Models.Patient", b =>
                {
                    b.HasOne("SE2025.Models.Gender", "Gender")
                        .WithMany("Patients")
                        .HasForeignKey("Gender_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SE2025.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SE2025.Models.User", b =>
                {
                    b.HasOne("SE2025.Models.User_Type", "User_Type")
                        .WithMany("Users")
                        .HasForeignKey("User_Type_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User_Type");
                });

            modelBuilder.Entity("SE2025.Models.Carer", b =>
                {
                    b.Navigation("Carer_Accesses");
                });

            modelBuilder.Entity("SE2025.Models.Gender", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("SE2025.Models.Patient", b =>
                {
                    b.Navigation("CarerAccess");
                });

            modelBuilder.Entity("SE2025.Models.User", b =>
                {
                    b.Navigation("Carer");
                });

            modelBuilder.Entity("SE2025.Models.User_Type", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
